### PR TITLE
Adjustments to number glyphs

### PR DESCRIPTION
**Pull request by drawcard**
I've concentrated on the number glyphs in this PR to optimise colour, curves and optical balance. I also adjusted the shapes slightly for the light versions, to smooth out curves and also improve interpolation with the new black shapes.

image

### CODE REVIEW

**Comment by drawcard** [comment]
I also just fixed a bit of uneven thickness in the upper part of /3/ that was catching my eye :)
image

**Review by erikdkennedy — COMMENTED** [review]
Is it typical to _not_ have the 6 and 9 be rotations of each other? e.g. do we generally prefer the bowl of the 6 to be a bit bigger than 9's, so the latter doesn't feel too top-heavy? That doesn't seem to be quite what you're doing here 🙂

**Comment by drawcard** [comment]
I think it probably depends on personal preferences, I had a look at the two reference fonts Montserrat and Karla to see how they handle this.

Montserrat does duplicate the /6/ and rotate it around to make a /9/, they have the component in the background layer and have redrawn the glyph from it:
Screen Shot 2021-06-17 at 11 00 10 am

However Karla have actually modified the curves of the /9/ slightly for optical balance - it may be also a stylistic choice. Here I've put the flipped /6/ is in the background layer to demonstrate:

image

It appears in Karla that the tail of the /9/ is modified a little to bring it in slightly more and close off the shape. And the bowl of the /9/ is also a bit higher than it would be in the /6/.

I'll let you make the final call about the approach :)

Also are you happy with the PRs being this size or do you prefer smaller PR's to seperate changes to each glyph?

**Comment by drawcard** [comment]
I also had a look at [Poppins](https://github.com/itfoundry/poppins), out of interest since it's a design that's close to Blueberry. They have just a slight difference between /6 and /9 - seems like the /9 is a little thicker in the top right and slightly less in the bottom left.

Screen Shot 2021-06-17 at 12 50 25 pm

**Pull request merged**
